"""add quantity column to orders table

Revision ID: 1ac4e5cd1ee6
Revises: 55eee27c42ab
Create Date: 2025-11-01 21:54:05.579228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac4e5cd1ee6'
down_revision: Union[str, Sequence[str], None] = '55eee27c42ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('inventory', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('reports', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('orders', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('admins', 'password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
