"""add quantity to orders

Revision ID: 55eee27c42ab
Revises: 46776ad5237c
Create Date: 2025-10-30 03:21:11.138894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55eee27c42ab'
down_revision: Union[str, Sequence[str], None] = '46776ad5237c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ✅ Sửa cột date từ string -> date
    op.alter_column(
        'orders',
        'date',
        existing_type=sa.VARCHAR(),
        type_=sa.Date(),
        nullable=False,
        postgresql_using="date::date"  # 🟢 Bắt buộc có dòng này
    )

    # ✅ Thêm cột quantity (nếu chưa có)
    op.add_column(
        'orders',
        sa.Column('quantity', sa.Integer(), nullable=True, server_default='1')
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('orders', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('orders', 'quantity')
    # ### end Alembic commands ###
